@startuml
classDiagram
    class SafariNavegador {
        +exibirPagina()
        +adicionarNovaAba()
        +atualizarPagina()
    }

    class Iphone {
        +main(String[] args)
        - navegador: SafariNavegador
        - ipod: ExecutarIpod
        - chamadas: ChamadasTelefonicas
    }

    class ExecutarIpod {
        +tocarMusica()
        +pausarMusica()
        +selecionarMusica()
    }

    class ChamadasTelefonicas {
        +ligar()
        +atender()
        +iniciarCorreioVoz()
    }

    Iphone -> SafariNavegador
    Iphone -> ExecutarIpod
    Iphone -> ChamadasTelefonicas

@enduml
